### ISSUE TITLE
Querying: Explicit (or auto-detected) batching field

### ISSUE THREAD

**Issue by arnodirlam** [infer-beam/infer#6]
Currently, the syntax for querying records as part of a rule result (`:query_one`, `:query_first` and `:query_all`) uses a keyword list for the condition, with an implicit `and` semantic:

```elixir
defmodule Todo.List do
  infer complete_tasks: {:query_all, Todo.Task, [list_id: {:ref, :id}, completed?: true]}
end
```

This is inconsistent with `and` conditions being written as maps in all other parts of Infer. The consequent syntax would be:

```elixir
defmodule Todo.List do
  infer complete_tasks: {:query_all, Todo.Task, %{list_id: {:ref, :id}, completed?: true}}
end

defmodule Todo.Task do
  infer completed?: true, when: %{completed_at: {:not, nil}}
  infer completed?: false
end
```

The reason for the current implementation is that we need to pick one part of the `and` condition for batching the internal Ecto query on. This is currently the first of part. In the example above, it would be `list_id: {:ref, id}`, so evaluating the rule for multiple `Todo.List` records would generate a query like

```sql
SELECT * FROM tasks WHERE completed_at IS NOT NULL AND list_id IN [1, 2, 4]
```

This allows users to hand-pick, which condition to use for batching. But it's very implicit and uses an inconsistent syntax.

## Migration

This change is backward-incompatible.

To migrate, adjust the syntax for all `:query_one`, `:query_first` and `:query_all` results.

## Implementation steps

The following steps could be implemented in separate PRs, if preferred.

- [ ] Explicit `batch_by` option

  The first and easiest step is to make the syntax consistent with the rest of Infer. The example above would become:

  ```elixir
  infer complete_tasks: {:query_all, Todo.Task, %{list_id: {:ref, :id}, completed?: true}, batch_by: :list_id}
  ```

- [ ] Automatic detection in simple cases

  Not all condition parts are applicable or make sense for batching. In the example above, `completed?` is a predicate, which is defined using a `:not` condition, which cannot be used for batching, since it's static.

  We _could_ also batch by `completed?: true`, but since the matching value is always `true` there wouldn't be any gain.

  The next step could thus be to look at all condition parts and only keep the ones that have a `:ref` in their value, because that makes them dynamic and thus candidates for batching.

  Then, if only one candidate remains, `batch_by` must be omitted.

- [ ] Automatic detection in complex cases

  If multiple condition parts remain as candidates for batching, the ideal solution is to implement a heuristic for picking the best-suited one. The best suited-suited condition part is the one that leads to the fewest batches. In other words, it's the one with the highest cardinality in values matched.

  For example, a condition matching `list_id` with the values `1, 2, 4` and `author_id` with the values `6, 6, 7` would pick the `list_id`, because it has 3 unique values ("cardinality") whereas `author_id` has only 2. The number of generated batches would thus be 2 (the number of different `author_id` values). When 3 or more condition parts are involved, it is necessary to count the number of unique **combinations** of values of the other parts.

  This implementation requires looking at the relevant values (with a cap, f.ex. 25) to determine the field with the highest cardinality.

  It should also support cases where the right side (matched value) is a list of multiple values, and flatten them for the cardinality detection.

  When this is implemented, `batch_by` becomes fully optional.
